spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yxtlms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefix:
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates/
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /static/**
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: templates/**
  redis:
    database: 0
    host: 192.168.129.129
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    lettuce:
      shutdown-timeout: 1000
#mybatis
mybatis:
  type-aliases-package: cn.imust.yxl_system.entity
  mapper-locations: classpath:mapper/*.xml
#mapper
mapper:
  mappers: cn.imust.yktlms.util.MyMapper
  not-empty: false
  identity: MYSQL
#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  port: 8080
  servlet:
    context-path: /